;/*FB_PKG_DELIM*/

__d("BarcelonaActivityFeedPageViewerQuery$Parameters",["cr:35642"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:35642")}),34);
__d("BarcelonaActivityFeedStoryListContainerQuery$Parameters",["cr:35649"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:35649")}),34);
__d("BarcelonaActivityFeedColumn.entrypoint",["BarcelonaActivityFeedPageViewerQuery$Parameters","BarcelonaActivityFeedStoryListContainerQuery$Parameters","BarcelonaGetActivityFilterConfig.entrypoint","JSResourceForInteraction"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){return{queries:{notificationsQueryRef:{parameters:r("BarcelonaActivityFeedStoryListContainerQuery$Parameters"),variables:t.routeParams.filter!=null?babelHelpers.extends({},o("BarcelonaGetActivityFilterConfig.entrypoint").getActivityFilterConfig(t.routeParams.filter)):{}},viewerQueryRef:{parameters:r("BarcelonaActivityFeedPageViewerQuery$Parameters"),variables:{}}}}},root:r("JSResourceForInteraction")("BarcelonaActivityFeedColumn.react").__setRef("BarcelonaActivityFeedColumn.entrypoint")};l.default=e}),98);
__d("BarcelonaActivityFeedColumnPage.entrypoint",["BarcelonaActivityFeedPageViewerQuery$Parameters","BarcelonaActivityFeedStoryListContainerQuery$Parameters","BarcelonaGetActivityFilterConfig.entrypoint","JSResourceForInteraction"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){return{queries:{notificationsQueryRef:{parameters:r("BarcelonaActivityFeedStoryListContainerQuery$Parameters"),variables:t.routeParams.filter!=null?babelHelpers.extends({},o("BarcelonaGetActivityFilterConfig.entrypoint").getActivityFilterConfig(t.routeParams.filter)):{}},viewerQueryRef:{parameters:r("BarcelonaActivityFeedPageViewerQuery$Parameters"),variables:{}}}}},root:r("JSResourceForInteraction")("BarcelonaActivityFeedColumnPage.react").__setRef("BarcelonaActivityFeedColumnPage.entrypoint")};l.default=e}),98);
__d("BarcelonaActivityFeedPageViewerQuery_threadsRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26868569202827091"}),null);
__d("BarcelonaActivityFeedPageViewerQuery$Parameters.threads",["BarcelonaActivityFeedPageViewerQuery_threadsRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("BarcelonaActivityFeedPageViewerQuery_threadsRelayOperation"),metadata:{is_distillery:!0,is_fully_www_executable:!0,root_field_name:["xdt_text_app_viewer"]},name:"BarcelonaActivityFeedPageViewerQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("BarcelonaActivityFeedStoryListContainerQuery_threadsRelayOperation",[],(function(t,n,r,o,a,i){a.exports="35829173386727876"}),null);
__d("BarcelonaActivityFeedStoryListContainerQuery$Parameters.threads",["BarcelonaActivityFeedStoryListContainerQuery_threadsRelayOperation","BarcelonaHasCommunityTopContributors.relayprovider","BarcelonaHasGhostPostEmojiActivation.relayprovider","BarcelonaHasMessaging.relayprovider"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("BarcelonaActivityFeedStoryListContainerQuery_threadsRelayOperation"),metadata:{is_distillery:!0,root_field_name:["xdt_api__v1__text_feed__notifications__connection"]},name:"BarcelonaActivityFeedStoryListContainerQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__BarcelonaHasCommunityTopContributorsrelayprovider:n("BarcelonaHasCommunityTopContributors.relayprovider"),__relay_internal__pv__BarcelonaHasMessagingrelayprovider:n("BarcelonaHasMessaging.relayprovider"),__relay_internal__pv__BarcelonaHasGhostPostEmojiActivationrelayprovider:n("BarcelonaHasGhostPostEmojiActivation.relayprovider")}}};a.exports=e}),null);
__d("BarcelonaDiscussionSummaries.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("gkx")("18550")}};l.default=e}),98);
__d("BarcelonaSearchRecommendedUsersQuery$Parameters",["cr:36737"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:36737")}),34);
__d("BarcelonaSearchSuggestedTopicsSectionQuery$Parameters",["cr:37531"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:37531")}),34);
__d("BarcelonaSearchTrendingTopicsV2SectionQuery$Parameters",["cr:36760"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:36760")}),34);
__d("getBarcelonaSearchTrendingTopicsPageSize.entrypointutils",["gkx"],(function(t,n,r,o,a,i,l){"use strict";function e(){return r("gkx")("10813")?15:5}l.getBarcelonaSearchTrendingTopicsPageSize=e}),98);
__d("BarcelonaSearchColumn.entrypoint",["BarcelonaSearchRecommendedUsersQuery$Parameters","BarcelonaSearchSuggestedTopicsSectionQuery$Parameters","BarcelonaSearchTrendingTopicsV2SectionQuery$Parameters","JSResourceForInteraction","cr:1457","getBarcelonaSearchTrendingTopicsPageSize.entrypointutils","gkx","qex"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(){var e={recommendedUsersQuery:{options:{},parameters:r("BarcelonaSearchRecommendedUsersQuery$Parameters"),variables:{}}};return r("BarcelonaSearchTrendingTopicsV2SectionQuery$Parameters")&&r("gkx")("18550")?e=babelHelpers.extends({},e,{trendingTopicsV2Query:{options:{},parameters:r("BarcelonaSearchTrendingTopicsV2SectionQuery$Parameters"),variables:{first:o("getBarcelonaSearchTrendingTopicsPageSize.entrypointutils").getBarcelonaSearchTrendingTopicsPageSize(),serp_prefetch:!0,surface_type:"search_tab"}}}):n("cr:1457")&&(e=babelHelpers.extends({},e,{trendingTopicsQuery:{options:{},parameters:n("cr:1457"),variables:{}}})),r("qex")._("5394")===!0&&(e=babelHelpers.extends({},e,{suggestedTopicsQuery:{options:{},parameters:r("BarcelonaSearchSuggestedTopicsSectionQuery$Parameters"),variables:{section:"recommended"}}})),{queries:e}},root:r("JSResourceForInteraction")("BarcelonaSearchColumn.react").__setRef("BarcelonaSearchColumn.entrypoint")};l.default=e}),98);
__d("BarcelonaSearchColumnPage.entrypoint",["BarcelonaSearchSuggestedTopicsSectionQuery$Parameters","BarcelonaSearchTrendingTopicsV2SectionQuery$Parameters","JSResourceForInteraction","cr:11431","cr:1457","getBarcelonaSearchTrendingTopicsPageSize.entrypointutils","gkx","qex"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e={};if(r("BarcelonaSearchTrendingTopicsV2SectionQuery$Parameters")&&r("gkx")("18550")?e=babelHelpers.extends({},e,{trendingTopicsV2Query:{options:{},parameters:r("BarcelonaSearchTrendingTopicsV2SectionQuery$Parameters"),variables:{first:o("getBarcelonaSearchTrendingTopicsPageSize.entrypointutils").getBarcelonaSearchTrendingTopicsPageSize(),serp_prefetch:!0,surface_type:"search_tab"}}}):n("cr:1457")&&(e=babelHelpers.extends({},e,{trendingTopicsQuery:{options:{},parameters:n("cr:1457"),variables:{}}})),n("cr:11431")){var a;e=babelHelpers.extends({},e,{recommendedUsersQuery:{options:{},parameters:n("cr:11431"),variables:{forced_user_ids:(a=t.routeParams.user_ids_string)==null?void 0:a.replace(/[\[\]]/g,"").split(",")}}})}return r("qex")._("5394")===!0&&(e=babelHelpers.extends({},e,{suggestedTopicsQuery:{options:{},parameters:r("BarcelonaSearchSuggestedTopicsSectionQuery$Parameters"),variables:{section:"recommended"}}})),{queries:e}},root:r("JSResourceForInteraction")("BarcelonaSearchColumnPage.react").__setRef("BarcelonaSearchColumnPage.entrypoint")};l.default=e}),98);
__d("BarcelonaSearchRecommendedUsersQuery_threadsRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26854203247564104"}),null);
__d("BarcelonaSearchRecommendedUsersQuery$Parameters.threads",["BarcelonaIsCrawler.relayprovider","BarcelonaIsLoggedIn.relayprovider","BarcelonaSearchRecommendedUsersQuery_threadsRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("BarcelonaSearchRecommendedUsersQuery_threadsRelayOperation"),metadata:{is_distillery:!0,root_field_name:["xdt_text_app_recommended_users"]},name:"BarcelonaSearchRecommendedUsersQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__BarcelonaIsLoggedInrelayprovider:n("BarcelonaIsLoggedIn.relayprovider"),__relay_internal__pv__BarcelonaIsCrawlerrelayprovider:n("BarcelonaIsCrawler.relayprovider")}}};a.exports=e}),null);
__d("BarcelonaSearchSuggestedTopicsSectionQuery$Parameters.threads",[],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:"35430854109862304",metadata:{},name:"BarcelonaSearchSuggestedTopicsSectionQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("BarcelonaSearchTrendingTopicsSectionQuery$Parameters",["cr:36756"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:36756")}),34);
__d("BarcelonaSearchTrendingTopicsSectionQuery_threadsRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26241423948866314"}),null);
__d("BarcelonaSearchTrendingTopicsSectionQuery$Parameters.threads",["BarcelonaSearchTrendingTopicsSectionQuery_threadsRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("BarcelonaSearchTrendingTopicsSectionQuery_threadsRelayOperation"),metadata:{is_distillery:!0,root_field_name:["xdt_api__v1__text_feed__trends"]},name:"BarcelonaSearchTrendingTopicsSectionQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("BarcelonaSearchTrendingTopicsV2SectionQuery$Parameters.threads",["BarcelonaDiscussionSummaries.relayprovider"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:"28085858231014199",metadata:{},name:"BarcelonaSearchTrendingTopicsV2SectionQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__BarcelonaDiscussionSummariesrelayprovider:n("BarcelonaDiscussionSummaries.relayprovider")}}};a.exports=e}),null);