;/*FB_PKG_DELIM*/

__d("BarcelonaFriendshipsDialogUserQuery$Parameters",["cr:35700"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:35700")}),34);
__d("BarcelonaFriendshipsFollowersTabQuery$Parameters",["cr:35712"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:35712")}),34);
__d("BarcelonaFriendshipsDialog.entrypoint",["BarcelonaFriendshipsDialogUserQuery$Parameters","BarcelonaFriendshipsFollowersTabQuery$Parameters","JSResourceForInteraction","gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){return{queries:{followersQueryRef:{parameters:r("BarcelonaFriendshipsFollowersTabQuery$Parameters"),variables:{first:20,userID:t.userID}},userQueryRef:{parameters:r("BarcelonaFriendshipsDialogUserQuery$Parameters"),variables:{shouldFetchMutualsCount:r("gkx")("21726"),userID:t.userID}}}}},root:r("JSResourceForInteraction")("BarcelonaFriendshipsDialog.react").__setRef("BarcelonaFriendshipsDialog.entrypoint")},s=e;l.default=s}),98);
__d("BarcelonaFriendshipsDialogUserQuery$Parameters.threads",["BarcelonaFriendshipsDialogUserQuery_threadsRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("BarcelonaFriendshipsDialogUserQuery_threadsRelayOperation"),metadata:{},name:"BarcelonaFriendshipsDialogUserQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("BarcelonaFriendshipsFollowersTabQuery$Parameters.threads",["BarcelonaFriendshipsFollowersTabQuery_threadsRelayOperation","BarcelonaIsCrawler.relayprovider","BarcelonaIsLoggedIn.relayprovider","BarcelonaShouldShowFediverseLists.relayprovider"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("BarcelonaFriendshipsFollowersTabQuery_threadsRelayOperation"),metadata:{is_distillery:!0,root_field_name:["fetch__XDTUserDict","xdt_api__v1__text_feed__user_counts"]},name:"BarcelonaFriendshipsFollowersTabQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__BarcelonaIsLoggedInrelayprovider:n("BarcelonaIsLoggedIn.relayprovider"),__relay_internal__pv__BarcelonaIsCrawlerrelayprovider:n("BarcelonaIsCrawler.relayprovider"),__relay_internal__pv__BarcelonaShouldShowFediverseListsrelayprovider:n("BarcelonaShouldShowFediverseLists.relayprovider")}}};a.exports=e}),null);
__d("BarcelonaIsSettings2PrivacyMigrationEnabled.relayprovider",["MetaConfig"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return r("MetaConfig")._("4")}};l.default=e}),98);
__d("BarcelonaProfileEditDialogQuery$Parameters",["cr:36564"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:36564")}),34);
__d("BarcelonaProfileEditDialog.entrypoint",["BarcelonaProfileEditDialogQuery$Parameters","JSResourceForInteraction"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(){return{queries:{queryRef:{options:{fetchPolicy:"network-only"},parameters:r("BarcelonaProfileEditDialogQuery$Parameters"),variables:{}}}}},root:r("JSResourceForInteraction")("BarcelonaProfileEditDialog.react").__setRef("BarcelonaProfileEditDialog.entrypoint")},s=e;l.default=s}),98);
__d("BarcelonaProfileEditDialogQuery_threadsRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26653295107705444"}),null);
__d("BarcelonaProfileEditDialogQuery$Parameters.threads",["BarcelonaHasCommunityTopContributors.relayprovider","BarcelonaHasEventBadge.relayprovider","BarcelonaIsSettings2PrivacyMigrationEnabled.relayprovider","BarcelonaProfileEditDialogQuery_threadsRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("BarcelonaProfileEditDialogQuery_threadsRelayOperation"),metadata:{is_distillery:!0,root_field_name:["xdt_text_app_viewer"]},name:"BarcelonaProfileEditDialogQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__BarcelonaHasEventBadgerelayprovider:n("BarcelonaHasEventBadge.relayprovider"),__relay_internal__pv__BarcelonaIsSettings2PrivacyMigrationEnabledrelayprovider:n("BarcelonaIsSettings2PrivacyMigrationEnabled.relayprovider"),__relay_internal__pv__BarcelonaHasCommunityTopContributorsrelayprovider:n("BarcelonaHasCommunityTopContributors.relayprovider")}}};a.exports=e}),null);
__d("useBarcelonaFollowRequestMutationApproveMutation.graphql",["cr:35745"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:35745")}),34);
__d("useBarcelonaFollowRequestMutationIgnoreMutation.graphql",["cr:35746"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:35746")}),34);
__d("useBarcelonaFollowRequestMutation_user.graphql",["cr:35747"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:35747")}),34);
__d("useBarcelonaFollowRequestMutation",["CometRelay","react-compiler-runtime","useBarcelonaFollowRequestMutationApproveMutation.graphql","useBarcelonaFollowRequestMutationIgnoreMutation.graphql","useBarcelonaFollowRequestMutation_user.graphql"],(function(t,n,r,o,a,i,l){"use strict";var e,s,u,c=e!==void 0?e:e=n("useBarcelonaFollowRequestMutation_user.graphql"),d=s!==void 0?s:s=n("useBarcelonaFollowRequestMutationApproveMutation.graphql"),m=u!==void 0?u:u=n("useBarcelonaFollowRequestMutationIgnoreMutation.graphql");function p(){var e=o("react-compiler-runtime").c(3),t=o("CometRelay").useMutation(d),n=t[0],r=o("CometRelay").useMutation(m),a=r[0],i;return e[0]!==n||e[1]!==a?(i=function(t,r,o){var e=r?n:a;e({onCompleted:o,optimisticResponse:{data:{user:{friendship_status:{followed_by:r,incoming_request:!1},id:t}}},variables:{target_user_id:t}})},e[0]=n,e[1]=a,e[2]=i):i=e[2],i}function _(e){var t=o("react-compiler-runtime").c(3),n=o("CometRelay").useFragment(c,e),r=p(),a=n.pk,i;return t[0]!==r||t[1]!==a?(i=function(t){r(a,t)},t[0]=r,t[1]=a,t[2]=i):i=t[2],i}l.APPROVE_MUTATION=d,l.IGNORE_MUTATION=m,l.useBarcelonaFollowRequestMutationByID=p,l.useBarcelonaFollowRequestMutation=_}),98);
__d("useBarcelonaFollowRequestMutationApproveMutation_threadsRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27417579857847310"}),null);
__d("useBarcelonaFollowRequestMutationApproveMutation.threads.graphql",["useBarcelonaFollowRequestMutationApproveMutation_threadsRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e=(function(){var e=[{defaultValue:null,kind:"LocalArgument",name:"target_user_id"}],t=[{kind:"Variable",name:"user_id",variableName:"target_user_id"}],r={alias:null,args:null,concreteType:"XDTRelationshipInfoDict",kind:"LinkedField",name:"friendship_status",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"followed_by",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"incoming_request",storageKey:null}],storageKey:null};return{fragment:{argumentDefinitions:e,kind:"Fragment",metadata:null,name:"useBarcelonaFollowRequestMutationApproveMutation",selections:[{alias:"data",args:t,concreteType:"XDTTextAppApproveUserFollowRequestResponse",kind:"LinkedField",name:"xdt_text_app_approve_user_follow_request",plural:!1,selections:[{alias:null,args:null,concreteType:"XDTUserDict",kind:"LinkedField",name:"user",plural:!1,selections:[r],storageKey:null}],storageKey:null}],type:"Mutation",abstractKey:null},kind:"Request",operation:{argumentDefinitions:e,kind:"Operation",name:"useBarcelonaFollowRequestMutationApproveMutation",selections:[{alias:"data",args:t,concreteType:"XDTTextAppApproveUserFollowRequestResponse",kind:"LinkedField",name:"xdt_text_app_approve_user_follow_request",plural:!1,selections:[{alias:null,args:null,concreteType:"XDTUserDict",kind:"LinkedField",name:"user",plural:!1,selections:[r,{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null}],storageKey:null}],storageKey:null}]},params:{id:n("useBarcelonaFollowRequestMutationApproveMutation_threadsRelayOperation"),metadata:{is_distillery:!0,root_field_name:["xdt_text_app_approve_user_follow_request"]},name:"useBarcelonaFollowRequestMutationApproveMutation",operationKind:"mutation",text:null}}})();a.exports=e}),null);
__d("useBarcelonaFollowRequestMutationIgnoreMutation_threadsRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27033417409602340"}),null);
__d("useBarcelonaFollowRequestMutationIgnoreMutation.threads.graphql",["useBarcelonaFollowRequestMutationIgnoreMutation_threadsRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e=(function(){var e=[{defaultValue:null,kind:"LocalArgument",name:"target_user_id"}],t=[{kind:"Variable",name:"user_id",variableName:"target_user_id"}],r={alias:null,args:null,concreteType:"XDTRelationshipInfoDict",kind:"LinkedField",name:"friendship_status",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"followed_by",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"incoming_request",storageKey:null}],storageKey:null};return{fragment:{argumentDefinitions:e,kind:"Fragment",metadata:null,name:"useBarcelonaFollowRequestMutationIgnoreMutation",selections:[{alias:"data",args:t,concreteType:"XDTTextAppIgnoreUserFollowRequestResponse",kind:"LinkedField",name:"xdt_text_app_ignore_user_follow_request",plural:!1,selections:[{alias:null,args:null,concreteType:"XDTUserDict",kind:"LinkedField",name:"user",plural:!1,selections:[r],storageKey:null}],storageKey:null}],type:"Mutation",abstractKey:null},kind:"Request",operation:{argumentDefinitions:e,kind:"Operation",name:"useBarcelonaFollowRequestMutationIgnoreMutation",selections:[{alias:"data",args:t,concreteType:"XDTTextAppIgnoreUserFollowRequestResponse",kind:"LinkedField",name:"xdt_text_app_ignore_user_follow_request",plural:!1,selections:[{alias:null,args:null,concreteType:"XDTUserDict",kind:"LinkedField",name:"user",plural:!1,selections:[r,{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null}],storageKey:null}],storageKey:null}]},params:{id:n("useBarcelonaFollowRequestMutationIgnoreMutation_threadsRelayOperation"),metadata:{is_distillery:!0,root_field_name:["xdt_text_app_ignore_user_follow_request"]},name:"useBarcelonaFollowRequestMutationIgnoreMutation",operationKind:"mutation",text:null}}})();a.exports=e}),null);
__d("useBarcelonaFollowRequestMutation_user.threads.graphql",[],(function(t,n,r,o,a,i){"use strict";var e={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useBarcelonaFollowRequestMutation_user",selections:[{kind:"RequiredField",field:{alias:null,args:null,kind:"ScalarField",name:"pk",storageKey:null},action:"THROW"}],type:"XDTUserDict",abstractKey:null};a.exports=e}),null);