;/*FB_PKG_DELIM*/

__d("BarcelonaComposerAttachmentConstants",["InstagramUserAgent"],(function(t,n,r,o,a,i,l){"use strict";var e=["image/avif","image/jpeg","image/png","image/webp"].concat(r("InstagramUserAgent").is_safari?["image/heif","image/heic"]:[]),s=[].concat(e,["video/mp4","video/quicktime","video/webm"]),u=[].concat(s,["image/gif"]);l.SUPPORTED_IMAGE_ATTACHMENT_MIME_TYPES=e,l.SUPPORTED_MEDIA_ATTACHMENT_MIME_TYPES=s,l.SUPPORTED_MESSAGING_ATTACHMENT_MIME_TYPES=u}),98);
__d("BarcelonaComposerLocationPickerQuery_threadsRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26804423055882904"}),null);
__d("BarcelonaComposerVariantContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).createContext,u=s({variant:null}),c=u;l.default=c}),98);
__d("BarcelonaDevToolsLoggerUtils",["BarcelonaWebStorage","BarcelonaWebStorageKey"],(function(t,n,r,o,a,i,l){"use strict";var e=null;function s(){if(e!=null)return e;try{var t=o("BarcelonaWebStorage").getSessionStorageForRead().getItem(r("BarcelonaWebStorageKey").CAN_LOG_TO_CONSOLE);return e=t==="true",e}catch(e){return!1}}function u(t){e=t,o("BarcelonaWebStorage").getSessionStorage().setItemGuarded(r("BarcelonaWebStorageKey").CAN_LOG_TO_CONSOLE,String(t))}function c(){try{var e=o("BarcelonaWebStorage").getSessionStorageForRead().getItem(r("BarcelonaWebStorageKey").CONSOLE_LOG_FILTER);return e}catch(e){return null}}function d(e){o("BarcelonaWebStorage").getSessionStorage().setItemGuarded(r("BarcelonaWebStorageKey").CONSOLE_LOG_FILTER,e)}function m(){try{var e=o("BarcelonaWebStorage").getSessionStorageForRead().getItem(r("BarcelonaWebStorageKey").IS_SUH_ENABLED);return e==="true"}catch(e){return!1}}function p(e){o("BarcelonaWebStorage").getSessionStorage().setItemGuarded(r("BarcelonaWebStorageKey").IS_SUH_ENABLED,String(e))}function _(){try{var e=o("BarcelonaWebStorage").getSessionStorageForRead().getItem(r("BarcelonaWebStorageKey").SUH_HOST);return e!=null?e:""}catch(e){return""}}function f(e){o("BarcelonaWebStorage").getSessionStorage().setItemGuarded(r("BarcelonaWebStorageKey").SUH_HOST,e.trim())}l.getCanLogToConsole=s,l.setCanLogToConsole=u,l.getConsoleLogFilter=c,l.setConsoleLogFilter=d,l.getIsSUHEnabled=m,l.setIsSUHEnabled=p,l.getSUHHost=_,l.setSUHHost=f}),98);
__d("BarcelonaEditProfileInterestsPageQuery_threadsRelayOperation",[],(function(t,n,r,o,a,i){a.exports="35611134185196737"}),null);
__d("BarcelonaMediaTypes",["$InternalEnum"],(function(t,n,r,o,a,i){"use strict";var e=n("$InternalEnum").Mirrored(["Image","Video"]),l=n("$InternalEnum")({FeedPost:"feed_post",ReplyPost:"reply_post"}),s=n("$InternalEnum")({Multimedia:"multimedia"});i.MediaType=e,i.MediaTargetSurface=l,i.MediaIngestSurface=s}),66);
__d("BarcelonaWebHost",[],(function(t,n,r,o,a,i){"use strict";function e(){var e=window.location.hostname;return e.startsWith("www.")&&e.endsWith(".threads.com")?"https://www.threads.com":"https://www.threads.net"}function l(){return e().replace(/^https?:\/\/(?:www\.)?/,"")}i.getBarcelonaProductionOrigin=e,i.getProductionHostWithoutSchemeAndWwwSubdomain=l}),66);
__d("Lexical",["cr:370"],(function(t,n,r,o,a,i){a.exports=n("cr:370")}),null);
__d("LexicalComposerContext",["cr:509"],(function(t,n,r,o,a,i){a.exports=n("cr:509")}),null);
__d("LexicalText",["cr:2181"],(function(t,n,r,o,a,i){a.exports=n("cr:2181")}),null);
__d("LexicalUtils",["cr:2774"],(function(t,n,r,o,a,i){a.exports=n("cr:2774")}),null);
__d("useBarcelonaComposerDialogVariant",["fbt","BarcelonaArrowLeftOutlineIcon.react","BarcelonaComposerConstants","BarcelonaComposerVariantContext","CometPressable.react","react","react-compiler-runtime","useBarcelonaIsSmallScreen"],(function(t,n,r,o,a,i,l,s){"use strict";var e,u=e||(e=o("react")),c=e.use;function d(e){var t=o("react-compiler-runtime").c(5),n=r("useBarcelonaIsSmallScreen")(),a=c(r("BarcelonaComposerVariantContext")),i=a.variant,l=n?o("BarcelonaComposerConstants").BarcelonaComposerVariant.FULLSCREEN:i!=null?i:o("BarcelonaComposerConstants").BarcelonaComposerVariant.TABBED_CARD,d;t[0]!==e?(d=e!=null?u.jsx(r("CometPressable.react"),{onPress:e,overlayDisabled:!0,children:u.jsx("div",{className:"x6s0dn4 x78zum5 xat8h9t",children:u.jsx(r("BarcelonaArrowLeftOutlineIcon.react"),{alt:s._(/*BTDS*/"\ub3cc\uc544\uac00\uae30"),color:"icon-primary",size:24})})}):u.jsx(u.Fragment,{}),t[0]=e,t[1]=d):d=t[1];var m;return t[2]!==d||t[3]!==l?(m={backButton:d,iconColor:"icon-primary",textColor:"simple_text",variant:l},t[2]=d,t[3]=l,t[4]=m):m=t[4],m}l.default=d}),226);
__d("usePopPage",["BaseMultiPageViewContext","FBLogger","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useCallback,c=s.useContext;function d(){var e,t=c(r("BaseMultiPageViewContext")),n=m;return t==null?n:(e=t.popPage)!=null?e:null}function m(){r("FBLogger")("BaseMultiPageView").mustfix("usePopPage can only be used inside BaseMultiPageView.")}l.default=d}),98);
__d("useBarcelonaComposerPushPageKeyCommands",["fbt","CometKeys","react-compiler-runtime","useKeyCommands","usePopPage"],(function(t,n,r,o,a,i,l,s){"use strict";function e(){var e=o("react-compiler-runtime").c(4),t=r("usePopPage")(),n,a;e[0]===Symbol.for("react.memo_cache_sentinel")?(n={key:r("CometKeys").ESCAPE},a=s._(/*BTDS*/"\ub3cc\uc544\uac00\uae30"),e[0]=n,e[1]=a):(n=e[0],a=e[1]);var i;e[2]!==t?(i=[{command:n,description:a,handler:function(){return t==null?void 0:t()}}],e[2]=t,e[3]=i):i=e[3];var l=i;r("useKeyCommands")(l)}l.default=e}),226);
__d("useFileDragEvents",["react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useCallback,c=s.useEffect,d=s.useRef,m=s.useState;function p(e,t,n){var r=o("react-compiler-runtime").c(13),a=t===void 0?document.documentElement:t,i=d(0),l=m(!1),s=l[0],u=l[1],p;r[0]!==e||r[1]!==n?(p=function(r){if(u(!1),(n==null||n(r))&&e!=null){r.preventDefault();var t=r.dataTransfer;if(t!=null){var o=t.files;e(o,r)!==!1&&r.stopPropagation()}else r.stopPropagation();i.current=0}},r[0]=e,r[1]=n,r[2]=p):p=r[2];var f=p,g;r[3]!==n?(g=function(t){var e,r=(e=t.dataTransfer)==null?void 0:e.files;(n==null||n(t))&&r!=null&&(t.preventDefault(),i.current=i.current+1,u(!0))},r[3]=n,r[4]=g):g=r[4];var h=g,y;r[5]!==n?(y=function(t){var e,r=(e=t.dataTransfer)==null?void 0:e.files;(n==null||n(t))&&r!=null&&(i.current=i.current-1)===0&&u(!1)},r[5]=n,r[6]=y):y=r[6];var C=y,b=_,v,S;return r[7]!==h||r[8]!==C||r[9]!==f||r[10]!==a?(v=function(){if(a!=null)return a.addEventListener("drop",f,!0),a.addEventListener("dragenter",h,!0),a.addEventListener("dragleave",C,!0),a.addEventListener("dragover",b,!0),(function(){a.removeEventListener("drop",f,!0),a.removeEventListener("dragenter",h,!0),a.removeEventListener("dragleave",C,!0),a.removeEventListener("dragover",b,!0)})},S=[h,C,b,f,a],r[7]=h,r[8]=C,r[9]=f,r[10]=a,r[11]=v,r[12]=S):(v=r[11],S=r[12]),c(v,S),s}function _(e){var t,n=(t=e.dataTransfer)==null?void 0:t.files;e.dataTransfer!=null&&(e.dataTransfer.dropEffect="copy"),n!=null&&e.preventDefault()}l.default=p}),98);